import type { Notification } from './types';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Checkout step 3 drop-off increased',
    description: 'Conversion rate declining significantly',
    timestamp: '2 mins ago',
    source: 'web',
    icon: 'info',
    read: false,
    priority: 'high',
  },
  {
    id: '2',
    title: 'Queue length exceeded threshold',
    description: 'Store backlog reached maximum',
    timestamp: '15 mins ago',
    source: 'cctv',
    icon: 'warning',
    read: false,
    priority: 'critical',
  },
  {
    id: '3',
    title: "Negative sentiment spike detected",
    description: 'Customer complaints trending upward',
    timestamp: '1 hr ago',
    source: 'social',
    icon: 'warning',
    read: false,
    priority: 'high',
  },
  {
    id: '4',
    title: 'Unusual traffic pattern detected',
    description: 'Bot activity suspected on site',
    timestamp: '2 hrs ago',
    source: 'web',
    icon: 'warning',
    read: true,
    priority: 'medium',
  },
  {
    id: '5',
    title: 'Loitering detected near entrance',
    description: 'Security alert at location',
    timestamp: '3 hrs ago',
    source: 'cctv',
    icon: 'error',
    read: true,
    priority: 'critical',
  },
  {
    id: '6',
    title: 'API response time degradation',
    description: 'Performance metrics below baseline',
    timestamp: '4 hrs ago',
    source: 'web',
    icon: 'warning',
    read: true,
    priority: 'medium',
  },
];
